/**
 * Formül kataloğu — Atolye_Gider_Model.xlsx FORMULLER sayfasının PES karşılığı.
 *
 * ÜRETİLMİŞ DOSYA: scripts/uret_formul_katalogu.mjs ile yeniden üretilir.
 * Elle düzenlenebilir ama Excel'den yeniden üretilince değişiklik kaybolur —
 * kalıcı düzeltme betiğin ESLEME tablosuna yazılmalı.
 *
 * NEDEN OKUNUR-YAZILAMAZ: Katalog hesabı YAPMAZ, anlatır. Bir satırı
 * veritabanından düzenlenebilir yapmak hesabı değiştirmez; yalnız
 * ekonomi-hesap.ts'ten sessizce sapan, doğru görünen yanlış bir belge üretir.
 * Değişebilen şey parametrelerdir (economy_param, /pes/ekonomi/parametre).
 *
 * girdiler BAŞLICA girdileri gösterir, tam liste olmak zorunda değil —
 * brüt gider gibi 27 kalemli satırlarda hepsini listelemek izi okunmaz yapar.
 */

/** Katalog girişinin geldiği Excel sayfası. Pano satırları 'PANO' altında toplanır. */
export type FormulKaynak = 'PARAMETRE' | 'HESAP' | 'MODEL_HESAP' | 'OZET' | 'PANO'

/** Hesap izinde gösterilecek bir girdi; anahtar değer havuzuna işaret eder. */
export type FormulGirdi = {
  etiket: string
  /** 'rasyo.<alan>' | 'param.<alan>' | 'giris.<alan>' | 'gider.<alan>' */
  anahtar: string
}

export type FormulGirdisi = {
  id: string
  kaynak: FormulKaynak
  etiket: string
  /** Sözel formül — Excel'in "Formül (sözle)" sütunu. */
  sozel: string
  /** Excel karşılığı; referans amaçlı, PES bunu çalıştırmaz. */
  excel: string | null
  /** "Nasıl okunur / neden" — eşikler, tipik aralıklar, bilinen tuzaklar. */
  okuma: string
  /**
   * Bu formülün hesapladığı EkonomiRasyo alanları (ya da marjSirasi /
   * fiyatEndeksi). Model ve pano satırlarında boş. Bölüm dakika maliyeti
   * gibi tek satırın üç alan ürettiği durumlar olduğu için dizi.
   */
  alanlar: string[]
  /** 'dosya#fonksiyon' — testle gerçekten dışa aktarıldığı doğrulanır. */
  kod: string | null
  girdiler: FormulGirdi[]
}

export const FORMUL_KATALOGU: FormulGirdisi[] = [
  {
    id: 'param.asgari-dk-nominal',
    kaynak: 'PARAMETRE',
    etiket: 'Asgari ücretli dakika maliyeti (nominal)',
    sozel: '(İşveren maliyeti − asgari ücret desteği) ÷ (nominal gün × günlük dakika)',
    excel: '=(B6-B7)/(B9*B8)',
    okuma: 'Türkiye\'de bir dikim dakikasının olabileceği en düşük maliyet: yasal olarak ödenen tek kişi, başka hiçbir yük yok. 2026: 37.953 ÷ 11.880 = 3,19 TL/dk.',
    alanlar: [],
    kod: 'lib/pes/ekonomi-hesap.ts#asgariDkMaliyetNominal',
    girdiler: [
      { etiket: 'İşveren maliyeti', anahtar: 'param.employer_cost' },
      { etiket: 'Asgari ücret desteği', anahtar: 'param.wage_support' },
      { etiket: 'Nominal gün', anahtar: 'param.nominal_days' },
      { etiket: 'Günlük dakika', anahtar: 'param.minutes_per_day' },
    ],
  },
  {
    id: 'param.asgari-dk-efektif',
    kaynak: 'PARAMETRE',
    etiket: 'Asgari ücretli dakika maliyeti (efektif)',
    sozel: 'Aynı pay ÷ (efektif gün × günlük dakika)',
    excel: '=(B6-B7)/(B10*B8)',
    okuma: 'Ücret 30 gün ödenir ama tatil, izin ve devamsızlık sonrası ~19,5 gün dikilir; efektif dakika ~%12 daha pahalıdır. Fiyatlama kararında bunu kullanın.',
    alanlar: [],
    kod: 'lib/pes/ekonomi-hesap.ts#asgariDkMaliyetEfektif',
    girdiler: [
      { etiket: 'İşveren maliyeti', anahtar: 'param.employer_cost' },
      { etiket: 'Asgari ücret desteği', anahtar: 'param.wage_support' },
      { etiket: 'Efektif gün', anahtar: 'param.effective_days' },
      { etiket: 'Günlük dakika', anahtar: 'param.minutes_per_day' },
    ],
  },
  {
    id: 'hesap.toplam-kisi',
    kaynak: 'HESAP',
    etiket: 'Toplam kişi',
    sozel: 'Kesim + dikim + UKP + ofis',
    excel: '=G+H+I+J (VERI_GIRIS)',
    okuma: 'Kişi başı rasyoların paydası.',
    alanlar: ['toplamKisi'],
    kod: 'lib/pes/ekonomi-hesap.ts#toplamKisi',
    girdiler: [
      { etiket: 'Kesim kişi', anahtar: 'giris.cutting_staff' },
      { etiket: 'Dikim kişi', anahtar: 'giris.sewing_staff' },
      { etiket: 'UKP kişi', anahtar: 'giris.ukp_staff' },
      { etiket: 'Ofis kişi', anahtar: 'giris.office_staff' },
    ],
  },
  {
    id: 'hesap.uretim-kisi',
    kaynak: 'HESAP',
    etiket: 'Üretim kişi',
    sozel: 'Kesim + dikim + UKP (ofis hariç)',
    excel: '=G+H+I',
    okuma: 'Dakika maliyetinin paydası: ofis dakikası ürün üretmez, maliyeti üretim dakikasına yüklenir.',
    alanlar: ['uretimKisi'],
    kod: 'lib/pes/ekonomi-hesap.ts#uretimKisi',
    girdiler: [
      { etiket: 'Kesim kişi', anahtar: 'giris.cutting_staff' },
      { etiket: 'Dikim kişi', anahtar: 'giris.sewing_staff' },
      { etiket: 'UKP kişi', anahtar: 'giris.ukp_staff' },
    ],
  },
  {
    id: 'hesap.dikim-payi',
    kaynak: 'HESAP',
    etiket: 'Dikim payı',
    sozel: 'Dikim kişi ÷ toplam kişi',
    excel: '=H/E',
    okuma: '%55–75 tipik. Düşükse bitim/ofis kadrosu ağır demektir; fiyat taşıyorsa sorun değil.',
    alanlar: ['dikimPayi'],
    kod: 'lib/pes/ekonomi-hesap.ts#dikimPayi',
    girdiler: [
      { etiket: 'Dikim kişi', anahtar: 'giris.sewing_staff' },
      { etiket: 'Toplam kişi', anahtar: 'rasyo.toplamKisi' },
    ],
  },
  {
    id: 'hesap.aylik-ciro',
    kaynak: 'HESAP',
    etiket: 'Aylık ciro',
    sozel: 'Fatura toplamı ÷ ay sayısı × (1 + boş gün ÷ 24)',
    excel: '=P/Q*(1+IF(adj=1,O/24,0))',
    okuma: 'Faturaya dayalı aylık ciro. Boş gün düzeltmesi, dışarı/boş geçen günleri kapasiteye geri ekler (ATOLYE VERİLER mantığı); PARAMETRE\'den kapatılabilir.',
    alanlar: ['aylikCiro'],
    kod: 'lib/pes/ekonomi-hesap.ts#aylikCiro',
    girdiler: [
      { etiket: 'Beyan edilen ciro', anahtar: 'giris.revenue_declared' },
      { etiket: 'Boş gün', anahtar: 'giris.idle_days' },
      { etiket: 'Düzeltme açık mı', anahtar: 'param.revenue_adj_on' },
      { etiket: 'Düzeltme paydası', anahtar: 'param.revenue_adj_divisor' },
    ],
  },
  {
    id: 'hesap.ort-fiyat-adet',
    kaynak: 'HESAP',
    etiket: 'Ortalama fiyat / adet',
    sozel: 'Aylık ciro ÷ aylık adet',
    excel: '=H/I',
    okuma: 'Atölyenin parça başına faturaladığı ortalama CMT. Adet bant kapasitesinden geldiği için tahminidir.',
    alanlar: ['ortFiyatAdet'],
    kod: 'lib/pes/ekonomi-hesap.ts#ortFiyatAdet',
    girdiler: [
      { etiket: 'Aylık ciro', anahtar: 'rasyo.aylikCiro' },
      { etiket: 'Aylık adet', anahtar: 'rasyo.aylikAdet' },
    ],
  },
  {
    id: 'hesap.brut-gider',
    kaynak: 'HESAP',
    etiket: 'Brüt gider',
    sozel: 'Maaş + mesai + prim + SGK + kıdem + 22 işletme gider satırının toplamı',
    excel: '=SUM(T:AS)',
    okuma: 'Formdaki 27 gider satırının hepsi.',
    alanlar: ['brutGider'],
    kod: 'lib/pes/ekonomi-hesap.ts#brutGider',
    girdiler: [
      { etiket: 'İşçilik toplamı (5 satır)', anahtar: 'rasyo.iscilikToplam' },
    ],
  },
  {
    id: 'hesap.net-gider',
    kaynak: 'HESAP',
    etiket: 'Net gider',
    sozel: 'Brüt gider − alınan teşvik',
    excel: '=K−L',
    okuma: 'Teşvik iade olarak geri geldiği için maliyetten düşülür (ATOLYE VERİLER kuralı). SGK brüt bildirilmişse doğru; net bildirilmişse teşvik iki kez düşülmüş olur — formda SGK brüt istenmeli.',
    alanlar: ['netGider'],
    kod: 'lib/pes/ekonomi-hesap.ts#netGider',
    girdiler: [
      { etiket: 'Brüt gider', anahtar: 'rasyo.brutGider' },
      { etiket: 'Alınan teşvik', anahtar: 'gider.incentive_amount' },
    ],
  },
  {
    id: 'hesap.kar-zarar',
    kaynak: 'HESAP',
    etiket: 'Kâr / zarar',
    sozel: 'Aylık ciro − net gider',
    excel: '=H−M',
    okuma: 'Atölyenin aylık faaliyet sonucu.',
    alanlar: ['karZarar'],
    kod: 'lib/pes/ekonomi-hesap.ts#karZarar',
    girdiler: [
      { etiket: 'Aylık ciro', anahtar: 'rasyo.aylikCiro' },
      { etiket: 'Net gider', anahtar: 'rasyo.netGider' },
    ],
  },
  {
    id: 'hesap.marj',
    kaynak: 'HESAP',
    etiket: 'Marj %',
    sozel: '(Ciro − net gider) ÷ ciro',
    excel: '=(H−M)/H',
    okuma: '+%10 üstü sağlıklı, −%10 … +%10 başabaş, −%10 altı zarar. Adet tahmininden etkilenmez (adet sadeleşir).',
    alanlar: ['marj'],
    kod: 'lib/pes/ekonomi-hesap.ts#marj',
    girdiler: [
      { etiket: 'Aylık ciro', anahtar: 'rasyo.aylikCiro' },
      { etiket: 'Net gider', anahtar: 'rasyo.netGider' },
    ],
  },
  {
    id: 'hesap.iscilik-toplam',
    kaynak: 'HESAP',
    etiket: 'İşçilik toplamı',
    sozel: 'Maaş + mesai + prim + SGK + kıdem',
    excel: '=SUM(T:X)',
    okuma: 'Personelle doğrudan ilgili beş satır.',
    alanlar: ['iscilikToplam'],
    kod: 'lib/pes/ekonomi-hesap.ts#iscilikToplam',
    girdiler: [],
  },
  {
    id: 'hesap.iscilik-payi',
    kaynak: 'HESAP',
    etiket: 'İşçilik payı (net)',
    sozel: '(İşçilik − teşvik) ÷ net gider',
    excel: '=(P−L)/M',
    okuma: 'Pilotta %66–79. Payın yüksekliği tek başına sorun değil; kişi başı ciroyla birlikte okunur.',
    alanlar: ['iscilikPayi'],
    kod: 'lib/pes/ekonomi-hesap.ts#iscilikPayi',
    girdiler: [
      { etiket: 'İşçilik toplamı', anahtar: 'rasyo.iscilikToplam' },
      { etiket: 'Alınan teşvik', anahtar: 'gider.incentive_amount' },
      { etiket: 'Net gider', anahtar: 'rasyo.netGider' },
    ],
  },
  {
    id: 'hesap.iscilik-disi-kisi',
    kaynak: 'HESAP',
    etiket: 'İşçilik dışı / kişi, kira hariç',
    sozel: '(Brüt gider − işçilik − kira) ÷ toplam kişi',
    excel: '=(K−P−AB)/E',
    okuma: 'Yemek, servis, enerji, sarf, bakım, idari: her çalışanla gelen işletme maliyeti. Pilot medyanı 12.831 TL; gider fonksiyonunun varsayılanı.',
    alanlar: ['iscilikDisiKisi'],
    kod: 'lib/pes/ekonomi-hesap.ts#iscilikDisiKisi',
    girdiler: [
      { etiket: 'Brüt gider', anahtar: 'rasyo.brutGider' },
      { etiket: 'İşçilik toplamı', anahtar: 'rasyo.iscilikToplam' },
      { etiket: 'Toplam kişi', anahtar: 'rasyo.toplamKisi' },
    ],
  },
  {
    id: 'hesap.ciro-kisi',
    kaynak: 'HESAP',
    etiket: 'Ciro / kişi',
    sozel: 'Aylık ciro ÷ toplam kişi',
    excel: '=H/E',
    okuma: 'Çalışan başına ekonomik çıktı. Pilotta marjla en güçlü ilişkiyi gösteren rasyo.',
    alanlar: ['ciroKisi'],
    kod: 'lib/pes/ekonomi-hesap.ts#ciroKisi',
    girdiler: [
      { etiket: 'Aylık ciro', anahtar: 'rasyo.aylikCiro' },
      { etiket: 'Toplam kişi', anahtar: 'rasyo.toplamKisi' },
    ],
  },
  {
    id: 'hesap.net-gider-kisi',
    kaynak: 'HESAP',
    etiket: 'Net gider / kişi',
    sozel: 'Net gider ÷ toplam kişi',
    excel: '=M/E',
    okuma: 'Ciro/kişi ile yan yana okunur: fark negatifse atölye kişi başına yeterli değer üretmiyor.',
    alanlar: ['netGiderKisi'],
    kod: 'lib/pes/ekonomi-hesap.ts#netGiderKisi',
    girdiler: [
      { etiket: 'Net gider', anahtar: 'rasyo.netGider' },
      { etiket: 'Toplam kişi', anahtar: 'rasyo.toplamKisi' },
    ],
  },
  {
    id: 'hesap.maas-kisi',
    kaynak: 'HESAP',
    etiket: 'Maaş / kişi',
    sozel: 'Net maaş toplamı ÷ toplam kişi',
    excel: '=T/E',
    okuma: 'Asgari net 28.075 TL (2026) ile kıyaslanır; altındaysa maaş eksik bildirilmiş olabilir.',
    alanlar: ['maasKisi'],
    kod: 'lib/pes/ekonomi-hesap.ts#maasKisi',
    girdiler: [
      { etiket: 'Toplam kişi', anahtar: 'rasyo.toplamKisi' },
      { etiket: 'Net asgari ücret (kıyas)', anahtar: 'param.min_wage_net' },
    ],
  },
  {
    id: 'hesap.adet-dikimci',
    kaynak: 'HESAP',
    etiket: 'Adet / dikimci',
    sozel: 'Aylık adet ÷ dikim kişi',
    excel: '=I/H',
    okuma: 'Ürüne çok bağlı (bebek parçası 1.000+, pantolon ~400); aynı klasman içinde kıyaslayın.',
    alanlar: ['adetDikimci'],
    kod: 'lib/pes/ekonomi-hesap.ts#adetDikimci',
    girdiler: [
      { etiket: 'Aylık adet', anahtar: 'rasyo.aylikAdet' },
      { etiket: 'Dikim kişi', anahtar: 'giris.sewing_staff' },
    ],
  },
  {
    id: 'hesap.nominal-dikim-dk',
    kaynak: 'HESAP',
    etiket: 'Nominal dikim dakikası / ay',
    sozel: 'Dikim kişi × günlük saat × nominal gün × 60',
    excel: '=H×K×M×60',
    okuma: 'Benchmark cetveli: herkes aynı 22 günle ölçülür.',
    alanlar: ['nominalDikimDk'],
    kod: 'lib/pes/ekonomi-hesap.ts#nominalDikimDk',
    girdiler: [
      { etiket: 'Dikim kişi', anahtar: 'giris.sewing_staff' },
      { etiket: 'Günlük saat', anahtar: 'giris.hours_per_day' },
      { etiket: 'Nominal gün', anahtar: 'giris.nominal_days' },
    ],
  },
  {
    id: 'hesap.fiili-dikim-dk',
    kaynak: 'HESAP',
    etiket: 'Fiili dikim dakikası / ay',
    sozel: 'Dikim kişi × günlük saat × fiili gün × 60',
    excel: '=H×K×N×60',
    okuma: 'Gerçek takvimle kapasite; fiyatlama için bu kullanılır.',
    alanlar: ['fiiliDikimDk'],
    kod: 'lib/pes/ekonomi-hesap.ts#fiiliDikimDk',
    girdiler: [
      { etiket: 'Dikim kişi', anahtar: 'giris.sewing_staff' },
      { etiket: 'Günlük saat', anahtar: 'giris.hours_per_day' },
      { etiket: 'Fiili gün', anahtar: 'giris.actual_days' },
    ],
  },
  {
    id: 'hesap.uretim-kisi-dk',
    kaynak: 'HESAP',
    etiket: 'Üretim kişi-dakikası',
    sozel: 'Üretim kişi × günlük saat × nominal gün × 60',
    excel: '=F×K×M×60',
    okuma: 'Kesim + dikim + UKP dakikalarının toplamı; bölüm dakika maliyetlerinin ortak paydası.',
    alanlar: ['uretimKisiDk'],
    kod: 'lib/pes/ekonomi-hesap.ts#uretimKisiDk',
    girdiler: [
      { etiket: 'Üretim kişi', anahtar: 'rasyo.uretimKisi' },
      { etiket: 'Günlük saat', anahtar: 'giris.hours_per_day' },
      { etiket: 'Nominal gün', anahtar: 'giris.nominal_days' },
    ],
  },
  {
    id: 'hesap.kisi-dk-maliyet',
    kaynak: 'HESAP',
    etiket: 'Kişi-dakika maliyeti',
    sozel: 'Net gider ÷ üretim kişi-dakikası',
    excel: '=M/Y',
    okuma: 'Bir üretim çalışanının bir dakikasının tam yüklü maliyeti (ofis, kira, enerji dahil).',
    alanlar: ['kisiDkMaliyet'],
    kod: 'lib/pes/ekonomi-hesap.ts#kisiDkMaliyet',
    girdiler: [
      { etiket: 'Net gider', anahtar: 'rasyo.netGider' },
      { etiket: 'Üretim kişi-dakikası', anahtar: 'rasyo.uretimKisiDk' },
    ],
  },
  {
    id: 'hesap.bolum-dk-maliyet',
    kaynak: 'HESAP',
    etiket: 'KESİM / DİKİM / UKP dk maliyeti',
    sozel: 'Net gider × bölüm ağırlığı ÷ (Σ(bölüm kişi × ağırlık) × günlük saat × gün × 60)',
    excel: '=M×w ÷ ((G·w_k+H·w_d+I·w_u)×K×M×60)',
    okuma: 'Net gider bölümlere maaş ağırlığıyla dağıtılır, sonra bölümün dakikasına bölünür. Ağırlıklar eşitken üç değer aynıdır; bölüm maaşları toplanınca PARAMETRE\'den ayrıştırılır. MODEL_HESAP bu üç değeri kullanır.',
    alanlar: ['kesimDkMaliyet', 'dikimDkMaliyet', 'ukpDkMaliyet'],
    kod: 'lib/pes/ekonomi-hesap.ts#bolumDkMaliyet',
    girdiler: [
      { etiket: 'Net gider', anahtar: 'rasyo.netGider' },
      { etiket: 'Kesim ağırlığı', anahtar: 'param.weight_cutting' },
      { etiket: 'Dikim ağırlığı', anahtar: 'param.weight_sewing' },
      { etiket: 'UKP ağırlığı', anahtar: 'param.weight_ukp' },
      { etiket: 'Üretim kişi-dakikası', anahtar: 'rasyo.uretimKisiDk' },
    ],
  },
  {
    id: 'hesap.dikim-dk-ciro',
    kaynak: 'HESAP',
    etiket: 'Dikim dk cirosu',
    sozel: 'Aylık ciro ÷ nominal dikim dakikası',
    excel: '=H/W',
    okuma: 'Bir dikim dakikasının kazandırdığı. Pilotta maliyet neredeyse düzken bu 5 kat değişiyordu: kârı belirleyen budur.',
    alanlar: ['dikimDkCiro'],
    kod: 'lib/pes/ekonomi-hesap.ts#dikimDkCiro',
    girdiler: [
      { etiket: 'Aylık ciro', anahtar: 'rasyo.aylikCiro' },
      { etiket: 'Nominal dikim dakikası', anahtar: 'rasyo.nominalDikimDk' },
    ],
  },
  {
    id: 'hesap.dakika-marji',
    kaynak: 'HESAP',
    etiket: 'Dakika marjı',
    sozel: '(Ciro − net gider) ÷ nominal dikim dakikası',
    excel: '=(H−M)/W',
    okuma: 'Dakika başına kâr ya da zarar, TL.',
    alanlar: ['dakikaMarji'],
    kod: 'lib/pes/ekonomi-hesap.ts#dakikaMarji',
    girdiler: [
      { etiket: 'Kâr / zarar', anahtar: 'rasyo.karZarar' },
      { etiket: 'Nominal dikim dakikası', anahtar: 'rasyo.nominalDikimDk' },
    ],
  },
  {
    id: 'hesap.fiili-dikim-dk-maliyet',
    kaynak: 'HESAP',
    etiket: 'Fiili dikim dk maliyeti',
    sozel: 'Net gider ÷ fiili dikim dakikası',
    excel: '=M/X',
    okuma: 'Gerçek takvimle dakika maliyeti; nominalden ~%10–15 yüksek.',
    alanlar: ['fiiliDikimDkMaliyet'],
    kod: 'lib/pes/ekonomi-hesap.ts#fiiliDikimDkMaliyet',
    girdiler: [
      { etiket: 'Net gider', anahtar: 'rasyo.netGider' },
      { etiket: 'Fiili dikim dakikası', anahtar: 'rasyo.fiiliDikimDk' },
    ],
  },
  {
    id: 'hesap.asgari-dk-carpani',
    kaynak: 'HESAP',
    etiket: 'Asgari dakika çarpanı',
    sozel: 'Dikim dk maliyeti (nominal, net gider ÷ dikim dk) ÷ asgari ücretli dakika',
    excel: '=(M/W)/PARAMETRE!B11',
    okuma: 'Dikim dakikasının asgari ücretli bir dakikanın kaç katı yük taşıdığı. ~1,3 yalın; 1,8–2,4 tipik; 3+ ağır (destek kadrosu, genel gider ya da boş zaman).',
    alanlar: ['asgariDkCarpani'],
    kod: 'lib/pes/ekonomi-hesap.ts#asgariDkCarpani',
    girdiler: [
      { etiket: 'Net gider', anahtar: 'rasyo.netGider' },
      { etiket: 'Nominal dikim dakikası', anahtar: 'rasyo.nominalDikimDk' },
      { etiket: 'İşveren maliyeti', anahtar: 'param.employer_cost' },
      { etiket: 'Nominal gün', anahtar: 'param.nominal_days' },
    ],
  },
  {
    id: 'hesap.dikim-dk-adet',
    kaynak: 'HESAP',
    etiket: 'Dikim dakikası / adet',
    sozel: 'Nominal dikim dakikası ÷ aylık adet',
    excel: '=W/I',
    okuma: '%100 verimlilikte parça başına düşen dikim dakikası; MTM ile kıyaslanınca gerçek verimliliği verir (MTM ÷ bu değer).',
    alanlar: ['dikimDkAdet'],
    kod: 'lib/pes/ekonomi-hesap.ts#dikimDkAdet',
    girdiler: [
      { etiket: 'Nominal dikim dakikası', anahtar: 'rasyo.nominalDikimDk' },
      { etiket: 'Aylık adet', anahtar: 'rasyo.aylikAdet' },
    ],
  },
  {
    id: 'hesap.basabas-fiyat',
    kaynak: 'HESAP',
    etiket: 'Başabaş fiyat / adet',
    sozel: 'Net gider ÷ aylık adet',
    excel: '=M/I',
    okuma: 'Bu karmada atölyenin sıfır kârla yaşadığı ortalama CMT.',
    alanlar: ['basabasFiyat'],
    kod: 'lib/pes/ekonomi-hesap.ts#basabasFiyat',
    girdiler: [
      { etiket: 'Net gider', anahtar: 'rasyo.netGider' },
      { etiket: 'Aylık adet', anahtar: 'rasyo.aylikAdet' },
    ],
  },
  {
    id: 'hesap.adil-fiyat',
    kaynak: 'HESAP',
    etiket: 'Adil fiyat / adet',
    sozel: 'Başabaş fiyat × (1 + hedef marj)',
    excel: '=AJ×(1+hedef)',
    okuma: 'Tedarikçiyi ayakta tutan fiyat; hedef marj PARAMETRE\'de (%15).',
    alanlar: ['adilFiyat'],
    kod: 'lib/pes/ekonomi-hesap.ts#adilFiyat',
    girdiler: [
      { etiket: 'Başabaş fiyat', anahtar: 'rasyo.basabasFiyat' },
      { etiket: 'Hedef marj', anahtar: 'param.target_margin' },
    ],
  },
  {
    id: 'hesap.fiyat-sapmasi',
    kaynak: 'HESAP',
    etiket: 'Fiyat sapması',
    sozel: 'Ortalama fiyat ÷ adil fiyat − 1',
    excel: '=J/AK−1',
    okuma: 'Negatifse atölye adilin altında çalışıyor (gizli pahalı: süreklilik riski); pozitifse pahalı ama yaşayabilir.',
    alanlar: ['fiyatSapmasi'],
    kod: 'lib/pes/ekonomi-hesap.ts#fiyatSapmasi',
    girdiler: [
      { etiket: 'Ortalama fiyat', anahtar: 'rasyo.ortFiyatAdet' },
      { etiket: 'Adil fiyat', anahtar: 'rasyo.adilFiyat' },
    ],
  },
  {
    id: 'hesap.iscilik-yuk',
    kaynak: 'HESAP',
    etiket: 'İşçilik yük katsayısı',
    sozel: '(İşçilik − teşvik) ÷ net maaş',
    excel: '=(P−L)/T',
    okuma: 'Net maaşın üstüne mesai, prim, SGK ve kıdemle ne kadar bindiği. Pilot: 6. bölge ~1,17, 1. bölge ~1,25. Gider fonksiyonunda kullanılır.',
    alanlar: ['iscilikYukKatsayisi'],
    kod: 'lib/pes/ekonomi-hesap.ts#iscilikYukKatsayisi',
    girdiler: [
      { etiket: 'İşçilik toplamı', anahtar: 'rasyo.iscilikToplam' },
      { etiket: 'Alınan teşvik', anahtar: 'gider.incentive_amount' },
    ],
  },
  {
    id: 'hesap.marj-sirasi',
    kaynak: 'HESAP',
    etiket: 'Marj sırası',
    sozel: 'Marjı kendisinden büyük olan atölye sayısı + 1',
    excel: '=COUNTIF(marj aralığı,">"&marj)+1',
    okuma: '1 = en kârlı. OZET sıralaması bunu okur.',
    alanlar: ['marjSirasi'],
    kod: 'lib/pes/ekonomi-akran.ts#marjSirasi',
    girdiler: [
      { etiket: 'Marj %', anahtar: 'rasyo.marj' },
    ],
  },
  {
    id: 'model.bolum-dk',
    kaynak: 'MODEL_HESAP',
    etiket: 'Bölüm dk maliyetleri',
    sozel: 'HESAP\'tan atölye adına göre çekilir',
    excel: '=INDEX(HESAP!kolon, MATCH(atölye, HESAP!kısa ad,0))',
    okuma: 'Atölye HESAP\'ta yoksa 0 gelir ve hüküm uyarır.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [],
  },
  {
    id: 'model.gercek-dakika',
    kaynak: 'MODEL_HESAP',
    etiket: 'Gerçek dakika / adet (kesim, dikim, UKP)',
    sozel: 'MTM (sn) ÷ 60 ÷ verimlilik; MTM boşsa kütüphane değeri',
    excel: '=MTM/60/verimlilik',
    okuma: 'Verimlilik = (üretilen adet × SAM) ÷ (operatör × çalışılan dakika). Kimse gün boyu standart hızda dikmez; %65 dikim varsayılanı PARAMETRE\'de.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#gercekDakika',
    girdiler: [
      { etiket: 'Dikim verimliliği', anahtar: 'param.eff_sewing' },
      { etiket: 'Kesim verimliliği', anahtar: 'param.eff_cutting' },
      { etiket: 'UKP verimliliği', anahtar: 'param.eff_ukp' },
    ],
  },
  {
    id: 'model.bolum-maliyet',
    kaynak: 'MODEL_HESAP',
    etiket: 'Bölüm maliyeti / adet',
    sozel: 'Gerçek dakika × bölüm dakika maliyeti',
    excel: '=dk × TL/dk',
    okuma: 'Üçünün toplamı = TOPLAM maliyet / adet. Genel gider dakika maliyetinin içinde; ayrıca eklenmez.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#bolumMaliyeti',
    girdiler: [],
  },
  {
    id: 'model.kar-zarar',
    kaynak: 'MODEL_HESAP',
    etiket: 'Kâr / zarar / adet',
    sozel: 'CMT fiyat − toplam maliyet',
    excel: '=O−N',
    okuma: 'Parça başına sonuç.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [],
  },
  {
    id: 'model.marj',
    kaynak: 'MODEL_HESAP',
    etiket: 'Marj %',
    sozel: 'Kâr ÷ CMT fiyat',
    excel: '=P/O',
    okuma: 'Hedef marjın (PARAMETRE) üstünde yeşil, 0–hedef sarı, negatif kırmızı.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [],
  },
  {
    id: 'model.adil-fiyat',
    kaynak: 'MODEL_HESAP',
    etiket: 'Adil fiyat',
    sozel: 'Toplam maliyet × (1 + hedef marj)',
    excel: '=N×(1+hedef)',
    okuma: 'Pazarlıkta referans: bu fiyatın altı atölyeyi zamanla zayıflatır.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [
      { etiket: 'Hedef marj', anahtar: 'param.target_margin' },
    ],
  },
  {
    id: 'model.gunluk-dk-ihtiyac',
    kaynak: 'MODEL_HESAP',
    etiket: 'Günlük dikim dakika ihtiyacı',
    sozel: 'Günlük adet × dikim gerçek dakikası',
    excel: '=adet × dk',
    okuma: 'İşin bir günde istediği dikim dakikası.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [],
  },
  {
    id: 'model.gunluk-kapasite',
    kaynak: 'MODEL_HESAP',
    etiket: 'Atölye günlük dikim kapasitesi',
    sozel: 'Dikim kişi × günlük saat × 60',
    excel: '=H×K×60 (VERI_GIRIS)',
    okuma: 'Atölyenin bir günde sunabildiği dikim dakikası.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [
      { etiket: 'Dikim kişi', anahtar: 'giris.sewing_staff' },
      { etiket: 'Günlük saat', anahtar: 'giris.hours_per_day' },
    ],
  },
  {
    id: 'model.kapasite-payi',
    kaynak: 'MODEL_HESAP',
    etiket: 'Kapasite payı',
    sozel: 'İhtiyaç ÷ kapasite',
    excel: '=T/U',
    okuma: '%100 üstü: iş bu günlük adetle sığmaz; adet düşürülür ya da bant büyütülür.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [],
  },
  {
    id: 'model.aylik-sonuc',
    kaynak: 'MODEL_HESAP',
    etiket: 'Aylık sonuç',
    sozel: 'Parça kârı × günlük adet × nominal gün',
    excel: '=P × adet × gün',
    okuma: 'İşin atölyeye aylık kazandırdığı / kaybettirdiği.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [],
  },
  {
    id: 'model.hukum',
    kaynak: 'MODEL_HESAP',
    etiket: 'Hüküm',
    sozel: 'Kapasite ve marj eşiklerine göre metin',
    excel: '=IF(...)',
    okuma: 'YEŞİL verilebilir; SARI adil fiyatı önerir; KIRMIZI başabaş ve adil fiyatı verir; "KAPASİTE AŞIMI" öne eklenir.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#hukum',
    girdiler: [],
  },
  {
    id: 'param.referans-3d',
    kaynak: 'PARAMETRE',
    etiket: '3D referans dk maliyeti (bölge)',
    sozel: 'Departmanın hesapladığı bölgesel dakika maliyeti; GÜNCEL sütunu kullanılır',
    excel: 'PARAMETRE!D32:D37',
    okuma: 'Şirket içi "Türkiye Dk Maliyet Değeri – 3D". Yeni dönem geldiğinde güncellenir; HESAP ve MODEL_HESAP bunu okur.',
    alanlar: [],
    kod: null,
    girdiler: [
      { etiket: 'Atölye bölgesi', anahtar: 'atolye.bolge' },
    ],
  },
  {
    id: 'hesap.referans-3d',
    kaynak: 'HESAP',
    etiket: '3D referans dk maliyeti',
    sozel: 'Atölyenin bölgesine göre PARAMETRE tablosundan çekilir',
    excel: '=INDEX(D32:D37, MATCH(bölge, A32:A37,0))',
    okuma: 'Bölge bazlı referans; atölyenin gerçekleşen dakikasıyla kıyaslanır.',
    alanlar: ['referans3D'],
    kod: null,
    girdiler: [
      { etiket: 'Atölye bölgesi', anahtar: 'atolye.bolge' },
    ],
  },
  {
    id: 'hesap.3d-oran',
    kaynak: 'HESAP',
    etiket: 'Dikim dk maliyeti ÷ 3D referans',
    sozel: 'Atölyenin gerçekleşen dikim dakika maliyeti ÷ bölge 3D değeri',
    excel: '=AC/AM',
    okuma: '1,00 = referansla aynı; 1,20 = referanstan %20 pahalı dakika; 0,85 = referansın altında (yalın ya da eksik bildirim).',
    alanlar: ['dkMaliyet3DOran'],
    kod: 'lib/pes/ekonomi-hesap.ts#dkMaliyet3DOran',
    girdiler: [
      { etiket: 'Dikim dk maliyeti', anahtar: 'rasyo.dikimDkMaliyet' },
      { etiket: '3D referans', anahtar: 'rasyo.referans3D' },
    ],
  },
  {
    id: 'model.referans-3d',
    kaynak: 'MODEL_HESAP',
    etiket: '3D referans maliyet / adet',
    sozel: '(Kesim + dikim + UKP MTM dakikası, verimlilik düzeltmesiz) × bölge 3D değeri',
    excel: '=Σ(MTM/60) × 3D',
    okuma: 'Şirketin kendi dakika değeriyle parça maliyeti; CMT teklifinin referans karşılığı. Varsayım: 3D değeri verimlilik kaybını zaten içerir (standart dakika ile çarpılır).',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [],
  },
  {
    id: 'model.cmt-3d-sapma',
    kaynak: 'MODEL_HESAP',
    etiket: 'CMT ÷ 3D referans − 1',
    sozel: 'Teklif fiyatının 3D referans maliyete göre sapması',
    excel: '=O/X−1',
    okuma: 'Pozitif: teklif referansın üstünde (atölye lehine); negatif: referansın altında.',
    alanlar: [],
    kod: 'lib/pes/model-fiyat.ts#modelFiyati',
    girdiler: [],
  },
  {
    id: 'ozet.medyan',
    kaynak: 'OZET',
    etiket: 'Medyan / en düşük / en yüksek',
    sozel: 'Cirosu olan atölyeler üzerinden MEDIAN / MIN / MAX',
    excel: '{=MEDIAN(IF(ciro>0, aralık))}',
    okuma: 'Benchmark = örneklem medyanı. 30+ atölyede aynı klasman / büyüklük / bölge akran grubuna geçilmeli.',
    alanlar: [],
    kod: 'lib/pes/ekonomi-akran.ts#medyan',
    girdiler: [],
  },
  {
    id: 'ozet.marj-siralamasi',
    kaynak: 'OZET',
    etiket: 'Marj sıralaması',
    sozel: 'Sıra numarasına göre HESAP\'tan çekilir',
    excel: '=INDEX(kolon, MATCH(sıra, marj sırası,0))',
    okuma: 'Sıralı liste; boş sıralar boş görünür.',
    alanlar: [],
    kod: 'lib/pes/ekonomi-akran.ts#marjSirasi',
    girdiler: [],
  },
  {
    id: 'pano.gider-fonksiyonu',
    kaynak: 'PANO',
    etiket: 'Tahmini aylık gider',
    sozel: 'Kişi × net maaş/kişi × yük katsayısı + kişi × işçilik dışı/kişi (kira hariç) + kira',
    excel: '=E×T×yük + E×nonlab + kira',
    okuma: 'Henüz anket yapılmamış atölye için 6 girdiyle tahmin. Pilot geri testi: ortalama hata %7, en kötü %17; maaş girilmezse ~%18.',
    alanlar: [],
    kod: null,
    girdiler: [
      { etiket: 'Maaş / kişi', anahtar: 'rasyo.maasKisi' },
      { etiket: 'İşçilik yük katsayısı', anahtar: 'rasyo.iscilikYukKatsayisi' },
      { etiket: 'İşçilik dışı / kişi', anahtar: 'rasyo.iscilikDisiKisi' },
    ],
  },
  {
    id: 'pano.yuzdelik-skor',
    kaynak: 'PANO',
    etiket: 'Yüzdelik skor (0–100)',
    sozel: 'Kendisinden kötü olan atölye sayısı ÷ (n−1) × 100',
    excel: '—',
    okuma: 'Üretkenlik = ciro/kişi, dk ciro, adet/dikimci ortalaması; Maliyet = düşük dk maliyet, düşük kişi maliyet; Ekonomik = marj, katma değer/kişi. Genel = %35 üretkenlik + %25 maliyet + %40 ekonomik.',
    alanlar: [],
    kod: 'lib/pes/ekonomi-akran.ts#yuzdelikSkor',
    girdiler: [],
  },
  {
    id: 'pano.fiyat-endeksi',
    kaynak: 'PANO',
    etiket: 'Fiyat endeksi',
    sozel: 'Dikim dk cirosu ÷ örneklem medyanı × 100',
    excel: '—',
    okuma: '115 üstü dakika başına pahalı, 85 altı ucuz. Yüksek fiyat + yüksek üretkenlik = faturada pahalı, toplam ekonomik maliyette ucuz.',
    alanlar: ['fiyatEndeksi'],
    kod: 'lib/pes/ekonomi-akran.ts#fiyatEndeksi',
    girdiler: [
      { etiket: 'Dikim dk cirosu', anahtar: 'rasyo.dikimDkCiro' },
    ],
  },
]

/** id → giriş. Derin bağlantı (?formul=hesap.marj) bunu kullanır. */
export function formulBul(id: string): FormulGirdisi | null {
  return FORMUL_KATALOGU.find((f) => f.id === id) ?? null
}

/** Bir rasyo alanının katalog girişi; radardan formüle geçiş için. */
export function alanFormulu(alan: string): FormulGirdisi | null {
  return FORMUL_KATALOGU.find((f) => f.alanlar.includes(alan)) ?? null
}
